name: getx_mvp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  dio: ^5.4.1
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7



  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/svg/


